### ISSUE TITLE
Keep main-app routing independent

### ISSUE THREAD

**Issue by cassiomansini** [marcellkiss/angular-web-component-example#3]
How could you do to the webcomponent routing doenst interfere on main-app routing?

**Comment by marcellkiss** [comment]
Overwrite the LocationStrategy with a NoopLocationStrategy in the web-component like this:
https://github.com/marcellkiss/angular-web-component-example/blob/master/apps/wc-app/src/app/app-routing.module.ts
This way, you can use Angular's RouterModule without modifying the url.

The url changes (read and write) should happen just and only by the host app.
